"""empty message

Revision ID: 3f9f74829af1
Revises: 3ea7a34f1f99
Create Date: 2025-10-20 08:18:49.840942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9f74829af1'
down_revision = '3ea7a34f1f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practical_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('selector', sa.String(length=200), nullable=True),
    sa.Column('attribute_name', sa.String(length=50), nullable=True),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['practical_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement')
    op.drop_table('practical_session')
    # ### end Alembic commands ###
