"""update note to quiz relationship

Revision ID: 439c884976a1
Revises: 313a5e74beab
Create Date: 2025-11-02 09:56:46.509931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439c884976a1'
down_revision = '313a5e74beab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['quiz_id'])
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['id'])

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('quiz_note_id_fkey'), type_='foreignkey')
        batch_op.drop_column('note_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('quiz_note_id_fkey'), 'note', ['note_id'], ['id'])

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('quiz_id')

    # ### end Alembic commands ###
