"""empty message

Revision ID: 43b18014ba77
Revises: 8537530f800c
Create Date: 2025-11-08 20:48:30.137901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b18014ba77'
down_revision = '8537530f800c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=150), nullable=True))

    # Update existing module rows with a unique slug based on their ID
    op.execute("UPDATE module SET slug = 'module-' || id WHERE slug IS NULL")

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.alter_column('slug', existing_type=sa.String(length=150), nullable=False)
        batch_op.create_unique_constraint('uq_module_slug', ['slug'])

    with op.batch_alter_table('submodule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=150), nullable=True))

    # Update existing submodule rows with a unique slug based on their ID
    op.execute("UPDATE submodule SET slug = 'submodule-' || id WHERE slug IS NULL")

    with op.batch_alter_table('submodule', schema=None) as batch_op:
        batch_op.alter_column('slug', existing_type=sa.String(length=150), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submodule', schema=None) as batch_op:
        batch_op.drop_column('slug')

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_constraint('uq_module_slug', type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
