"""Add Course model

Revision ID: 474bbf2c6928
Revises: aa911780fda2
Create Date: 2025-11-01 06:22:31.679143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474bbf2c6928'
down_revision = 'aa911780fda2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
