"""Add content_path to ModuleItem and make content_id nullable

Revision ID: 54bc4b64d3f5
Revises: 5682d5522783
Create Date: 2025-11-08 19:12:52.059004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54bc4b64d3f5'
down_revision = '5682d5522783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_item', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('content_path')

    # ### end Alembic commands ###
