"""Add certificate_name to Certificate model

Revision ID: 67452db6e2c9
Revises: a9f9246a344f
Create Date: 2025-11-02 11:23:13.707325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67452db6e2c9'
down_revision = 'a9f9246a344f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('certificate_name')

    # ### end Alembic commands ###
