"""Add category to Quiz model

Revision ID: 7f00f7b27c46
Revises: 6e7485bf7e50
Create Date: 2025-10-19 12:58:05.338904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f00f7b27c46'
down_revision = '6e7485bf7e50'
branch_labels = None
depends_on = None


# Inside 7f00f7b27c46_add....py

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        # --- MODIFIED LINE ---
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False, server_default='Quiz'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
