"""Add parent_id to Submodule for nested submodules

Revision ID: e0d611e25c56
Revises: 474bbf2c6928
Create Date: 2025-11-01 06:28:34.569656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d611e25c56'
down_revision = '474bbf2c6928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submodule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'submodule', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submodule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
