"""empty message

Revision ID: f6e6ed462afa
Revises: 43b18014ba77
Create Date: 2025-11-09 00:59:26.263625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e6ed462afa'
down_revision = '43b18014ba77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
    op.execute("UPDATE module_item SET is_published = FALSE WHERE is_published IS NULL")
    with op.batch_alter_table('module_item', schema=None) as batch_op:
        batch_op.alter_column('is_published', nullable=False)

    with op.batch_alter_table('submodule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
    op.execute("UPDATE submodule SET is_published = FALSE WHERE is_published IS NULL")
    with op.batch_alter_table('submodule', schema=None) as batch_op:
        batch_op.alter_column('is_published', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submodule', schema=None) as batch_op:
        batch_op.drop_column('is_published')

    with op.batch_alter_table('module_item', schema=None) as batch_op:
        batch_op.drop_column('is_published')

    # ### end Alembic commands ###
