"""Add profile fields to User model

Revision ID: f99e5aa52cac
Revises: 67452db6e2c9
Create Date: 2025-11-02 12:38:06.795555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99e5aa52cac'
down_revision = '67452db6e2c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        # Add profile_image_file as nullable first
        batch_op.add_column(sa.Column('profile_image_file', sa.String(length=20), nullable=True))

    # Update existing rows to set a default value for profile_image_file
    op.execute("UPDATE \"user\" SET profile_image_file = 'default.jpg' WHERE profile_image_file IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Then alter the column to be non-nullable
        batch_op.alter_column('profile_image_file',
                              existing_type=sa.String(length=20),
                              nullable=False,
                              existing_nullable=True,
                              server_default='default.jpg') # Add server_default for new rows

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image_file')
        batch_op.drop_column('bio')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
